const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{health: 0},
	{overlap: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{Player: 0},
	{Solid: 0},
	{Platforms: 0},
	{key: 0},
	{ENEMY: 0},
	{Mouse: 0},
	{Stars: 0},
	{Particles: 0},
	{Particles2: 0},
	{kills: 0},
	{killsAmount: 0},
	{Text: 0},
	{Text2: 0},
	{HealthBar: 0},
	{Healthp: 0},
	{KillCount: 0},
	{StarsAmount: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Platforms: class extends self.ISpriteInstance {},
	key: class extends self.IInstance {},
	ENEMY: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Stars: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	kills: class extends self.ITextInstance {},
	killsAmount: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	health: class extends self.ISpriteInstance {},
	Healthp: class extends self.IParticlesInstance {}
}